apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zidv2hpqs-go 
  janus-idp.io/tekton: zidv2hpqs-go
  backstage.io/kubernetes-id: zidv2hpqs-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zidv2hpqs-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml