apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zidv2hpqs-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zidv2hpqs-go 
  name: zidv2hpqs-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zidv2hpqs-go 
